version: "3"

services:
  db:
    image: postgres
    restart: unless-stopped
    networks: 
      - default
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "postgres"
  app:
    restart: unless-stopped
    build: ./votingsite
    volumes:
      - ./media:/srv/media
      - static-data:/srv/static
    env_file: .env
    labels:
      traefik.enable: "false"
    networks:
      - default
      - web
    links:
      - db
    depends_on:
      - db

  front:
    image: nginx
    restart: unless-stopped
    volumes:
      - ./media:/srv/media
      - static-data:/srv/static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.voter.rule=Host(`$HOSTNAME`)"
      - "traefik.http.routers.voter.entrypoints=$TRAEFIK_ENTRYPOINT"
      - "traefik.http.routers.voter.tls.certresolver=$TRAEFIK_CERTRESOLVER"
      - "traefik.http.services.voter.loadbalancer.server.port=80"
    depends_on:
      - app
    networks:
      - web

volumes:
  static-data:
  postgres-data:

networks:
  web:
    external: true
